pipeline{
    agent any
    environment{
        staging_server="172.31.16.139"
    }

    stages{
        stage('Deploy to remote'){
            steps{
                sh 'scp ${WORKSPACE}/* ROOT@${staging_server}:/var/www/html/myphp/'
            }
        }
    }
}
